//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoletasVendidas
    {
        public long RowIDBoleta { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<System.TimeSpan> HoraInicialFuncion { get; set; }
        public string NombreSala { get; set; }
        public string FormatoVersion { get; set; }
        public string TituloLocal { get; set; }
        public string NombreTarifa { get; set; }
        public Nullable<int> PrecioVenta { get; set; }
        public string SillaVendida { get; set; }
        public string InformacionTaquillero { get; set; }
        public string PrefijoTaquilla { get; set; }
        public Nullable<System.DateTime> FechaFuncion { get; set; }
        public string NombreTaquilla { get; set; }
    }
}
