//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public Ciudad()
        {
            this.ClienteRoyal = new HashSet<ClienteRoyal>();
            this.Tercero = new HashSet<Tercero>();
            this.Teatro = new HashSet<Teatro>();
        }
    
        public int RowID { get; set; }
        public int DepartamentoID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> RowIDCreacion { get; set; }
        public Nullable<int> TeatroCreacion { get; set; }
        public string CreadoPor { get; set; }
        public string ModificadoPor { get; set; }
    
        public virtual ICollection<ClienteRoyal> ClienteRoyal { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual ICollection<Tercero> Tercero { get; set; }
        public virtual ICollection<Teatro> Teatro { get; set; }
    }
}
