//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteRoyal
    {
        public ClienteRoyal()
        {
            this.TarjetaMembresiaClienteRoyal = new HashSet<TarjetaMembresiaClienteRoyal>();
        }
    
        public int RowID { get; set; }
        public string Documento { get; set; }
        public string CorreoElectronico { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> RecibirInformacion { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> CiudadResidenciaID { get; set; }
        public Nullable<int> GeneroID { get; set; }
        public Nullable<int> ClasificacionID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<int> preferenciasID { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Opcion Opcion1 { get; set; }
        public virtual ICollection<TarjetaMembresiaClienteRoyal> TarjetaMembresiaClienteRoyal { get; set; }
        public virtual Opcion Opcion2 { get; set; }
    }
}
