//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlCajaUsuarioRecibe
    {
        public int RowID { get; set; }
        public double ValorEntrega { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<int> CantidadTarjetas { get; set; }
        public Nullable<int> CantidadBonoRegalo { get; set; }
        public Nullable<int> CantidadGafasAd { get; set; }
        public Nullable<int> CantidadGafasNin { get; set; }
        public Nullable<int> ControlCajaEntregaID { get; set; }
    
        public virtual ControlCajaUsuarioEntrega ControlCajaUsuarioEntrega { get; set; }
    }
}
