//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elenco
    {
        public int RowId { get; set; }
        public int TipoElencoID { get; set; }
        public int EncabezadoPeliculaID { get; set; }
        public string Nombre { get; set; }
    
        public virtual Opcion Opcion { get; set; }
        public virtual EncabezadoPelicula EncabezadoPelicula { get; set; }
    }
}
