//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncabezadoVentaEmpresarial
    {
        public EncabezadoVentaEmpresarial()
        {
            this.DetalleVentaEmpresarial = new HashSet<DetalleVentaEmpresarial>();
            this.TeatroVentaEmpresarial = new HashSet<TeatroVentaEmpresarial>();
        }
    
        public int RowID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> TerceroID { get; set; }
        public Nullable<int> FormatoID { get; set; }
        public Nullable<int> ClasificacionID { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Opcion Opcion1 { get; set; }
        public virtual Tercero Tercero { get; set; }
        public virtual ICollection<DetalleVentaEmpresarial> DetalleVentaEmpresarial { get; set; }
        public virtual ICollection<TeatroVentaEmpresarial> TeatroVentaEmpresarial { get; set; }
    }
}
