//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvidenciaPqrs
    {
        public int RowId { get; set; }
        public string Archivo { get; set; }
        public Nullable<int> PqrsID { get; set; }
    
        public virtual Pqrs Pqrs { get; set; }
    }
}
