//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcion
    {
        public Funcion()
        {
            this.BoletaVendida = new HashSet<BoletaVendida>();
            this.ListaPrecioFuncion = new HashSet<ListaPrecioFuncion>();
        }
    
        public int RowID { get; set; }
        public int EncabezadoProgramacionID { get; set; }
        public Nullable<int> DetallePeliculaID { get; set; }
        public int SalaID { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public Nullable<short> TiempoAseo { get; set; }
        public Nullable<short> TiempoCorto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> Sincronizado { get; set; }
        public Nullable<System.TimeSpan> HoraInicial { get; set; }
        public Nullable<System.TimeSpan> HoraFinal { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual DetallePelicula DetallePelicula { get; set; }
        public virtual EncabezadoProgramacion EncabezadoProgramacion { get; set; }
        public virtual ICollection<BoletaVendida> BoletaVendida { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual ICollection<ListaPrecioFuncion> ListaPrecioFuncion { get; set; }
    }
}
