//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaDetalle
    {
        public ListaDetalle()
        {
            this.ListaPrecioFuncion = new HashSet<ListaPrecioFuncion>();
            this.BoletaVendida = new HashSet<BoletaVendida>();
            this.DetalleVentaEmpresarial = new HashSet<DetalleVentaEmpresarial>();
        }
    
        public int RowID { get; set; }
        public int ListaEncabezadoID { get; set; }
        public Nullable<int> TipoFormatoID { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public Nullable<System.TimeSpan> HoraInicial { get; set; }
        public Nullable<System.TimeSpan> HoraFinal { get; set; }
        public string DiasAsignados { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> PrecioDistribuidor { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> Sincronizado { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> TipoServicioID { get; set; }
        public Nullable<int> TipoListaDetalle { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Opcion Opcion1 { get; set; }
        public virtual Opcion Opcion2 { get; set; }
        public virtual ICollection<ListaPrecioFuncion> ListaPrecioFuncion { get; set; }
        public virtual ICollection<BoletaVendida> BoletaVendida { get; set; }
        public virtual ICollection<DetalleVentaEmpresarial> DetalleVentaEmpresarial { get; set; }
        public virtual ListaEncabezado ListaEncabezado { get; set; }
    }
}
