//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaEncabezado
    {
        public ListaEncabezado()
        {
            this.OportunidadVenta = new HashSet<OportunidadVenta>();
            this.ListaDetalle = new HashSet<ListaDetalle>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> Sincronizado { get; set; }
        public Nullable<int> TeatroID { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
    
        public virtual ICollection<OportunidadVenta> OportunidadVenta { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Teatro Teatro { get; set; }
        public virtual ICollection<ListaDetalle> ListaDetalle { get; set; }
    }
}
