//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.RolMenu = new HashSet<RolMenu>();
        }
    
        public int RowID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string URL { get; set; }
        public int TipoMenuID { get; set; }
        public string Imagen { get; set; }
        public bool Activo { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> Sincronizado { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        public virtual Tipo Tipo1 { get; set; }
        public virtual TipoMenu TipoMenu { get; set; }
        public virtual ICollection<RolMenu> RolMenu { get; set; }
    }
}
