//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OportunidadVenta
    {
        public int RowID { get; set; }
        public Nullable<int> ProspectoID { get; set; }
        public Nullable<int> TeatroID { get; set; }
        public Nullable<int> ContactoID { get; set; }
        public string Titulo { get; set; }
        public string Valor { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<System.DateTime> FechaCierra { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<int> ListaPrecioID { get; set; }
        public string Descripcion { get; set; }
        public int EstadoID { get; set; }
        public string vendedor { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string CreadoPor { get; set; }
        public string UsuarioMod { get; set; }
        public Nullable<System.DateTime> fechaMod { get; set; }
    
        public virtual Contacto Contacto { get; set; }
        public virtual ListaEncabezado ListaEncabezado { get; set; }
        public virtual Tercero Tercero { get; set; }
        public virtual Teatro Teatro { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
