//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pqrs
    {
        public Pqrs()
        {
            this.EvidenciaPqrs = new HashSet<EvidenciaPqrs>();
            this.Seguimiento = new HashSet<Seguimiento>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> TeatroID { get; set; }
        public Nullable<int> TipoSolicitudID { get; set; }
        public Nullable<int> TerceroID { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaSuceso { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Teatro Teatro { get; set; }
        public virtual Tercero Tercero { get; set; }
        public virtual ICollection<EvidenciaPqrs> EvidenciaPqrs { get; set; }
        public virtual TipoSolicitud TipoSolicitud { get; set; }
        public virtual ICollection<Seguimiento> Seguimiento { get; set; }
    }
}
