//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.ProductoVendido = new HashSet<ProductoVendido>();
        }
    
        public int RowID { get; set; }
        public string NombreProducto { get; set; }
        public string Referencia { get; set; }
        public int Rowid_erp { get; set; }
        public string Descripcion { get; set; }
        public int Costo { get; set; }
        public Nullable<System.DateTime> FechaUltimaSincronizacion { get; set; }
    
        public virtual ICollection<ProductoVendido> ProductoVendido { get; set; }
    }
}
