//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoVendido
    {
        public int Rowid { get; set; }
        public int ProductoID { get; set; }
        public int ControlIngresoID { get; set; }
        public short Cantidad { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual ControlIngreso ControlIngreso { get; set; }
    }
}
