//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public Reserva()
        {
            this.BoletaReservada = new HashSet<BoletaReservada>();
        }
    
        public int RowID { get; set; }
        public string CodigoReserva { get; set; }
        public string ClienteID { get; set; }
        public string NombresCliente { get; set; }
        public string TelefonoCliente { get; set; }
        public Nullable<System.DateTime> FechaReserva { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual ICollection<BoletaReservada> BoletaReservada { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Estado Estado1 { get; set; }
    }
}
