//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        public Sala()
        {
            this.Funcion = new HashSet<Funcion>();
            this.FormatoSala = new HashSet<FormatoSala>();
            this.MapaSala = new HashSet<MapaSala>();
            this.ServicioSala = new HashSet<ServicioSala>();
        }
    
        public int RowID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> TipoAudioID { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public int TeatroID { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> Sincronizado { get; set; }
        public Nullable<int> Cantidad_Filas { get; set; }
        public Nullable<int> Cantidad_Columnas { get; set; }
        public Nullable<int> Capacidad { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Teatro Teatro { get; set; }
        public virtual ICollection<Funcion> Funcion { get; set; }
        public virtual ICollection<FormatoSala> FormatoSala { get; set; }
        public virtual ICollection<MapaSala> MapaSala { get; set; }
        public virtual ICollection<ServicioSala> ServicioSala { get; set; }
    }
}
