//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SillaBloqueo
    {
        public int RowID { get; set; }
        public int SillaID { get; set; }
        public int FuncionId { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaBloqueo { get; set; }
        public Nullable<int> UsuarioBloqueoID { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual UsuarioSistema UsuarioSistema { get; set; }
        public virtual Funcion Funcion { get; set; }
        public virtual MapaSala MapaSala { get; set; }
    }
}
