//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taquilla
    {
        public Taquilla()
        {
            this.BoletaVendida = new HashSet<BoletaVendida>();
            this.BoletaReservada = new HashSet<BoletaReservada>();
        }
    
        public int RowID { get; set; }
        public int TeatroID { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public string Nombre { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> Sincronizado { get; set; }
        public string IP { get; set; }
        public string Prefijo { get; set; }
        public Nullable<int> RowIDCentral { get; set; }
        public string ConsecutivoInicial { get; set; }
        public string ConsecutivoFinal { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> TipoTaquillaID { get; set; }
        public Nullable<int> RowIDCreacion { get; set; }
        public Nullable<int> TeatroCreacion { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Teatro Teatro { get; set; }
        public virtual ICollection<BoletaVendida> BoletaVendida { get; set; }
        public virtual ICollection<BoletaReservada> BoletaReservada { get; set; }
    }
}
