//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetaMembresia
    {
        public TarjetaMembresia()
        {
            this.TarjetaMembresiaClienteRoyal = new HashSet<TarjetaMembresiaClienteRoyal>();
        }
    
        public int RowID { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<short> NoRedenciones { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual ICollection<TarjetaMembresiaClienteRoyal> TarjetaMembresiaClienteRoyal { get; set; }
    }
}
