//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeatroVentaEmpresarial
    {
        public int RowID { get; set; }
        public int VentaEncabezadoID { get; set; }
        public int TeatroID { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Teatro Teatro { get; set; }
        public virtual EncabezadoVentaEmpresarial EncabezadoVentaEmpresarial { get; set; }
    }
}
