//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teatro
    {
        public Teatro()
        {
            this.DetalleConvenio = new HashSet<DetalleConvenio>();
            this.OportunidadVenta = new HashSet<OportunidadVenta>();
            this.EncabezadoProgramacion = new HashSet<EncabezadoProgramacion>();
            this.ListaEncabezado = new HashSet<ListaEncabezado>();
            this.Pqrs = new HashSet<Pqrs>();
            this.Sala = new HashSet<Sala>();
            this.Taquilla = new HashSet<Taquilla>();
            this.TeatroPelicula = new HashSet<TeatroPelicula>();
            this.TeatroVentaEmpresarial = new HashSet<TeatroVentaEmpresarial>();
            this.UsuarioSistema = new HashSet<UsuarioSistema>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> CompaniaID { get; set; }
        public string CentroOperacion { get; set; }
        public string IP { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CiudadID { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> EstadoID { get; set; }
    
        public virtual ICollection<DetalleConvenio> DetalleConvenio { get; set; }
        public virtual ICollection<OportunidadVenta> OportunidadVenta { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual ICollection<EncabezadoProgramacion> EncabezadoProgramacion { get; set; }
        public virtual ICollection<ListaEncabezado> ListaEncabezado { get; set; }
        public virtual ICollection<Pqrs> Pqrs { get; set; }
        public virtual ICollection<Sala> Sala { get; set; }
        public virtual ICollection<Taquilla> Taquilla { get; set; }
        public virtual Tercero Tercero { get; set; }
        public virtual ICollection<TeatroPelicula> TeatroPelicula { get; set; }
        public virtual ICollection<TeatroVentaEmpresarial> TeatroVentaEmpresarial { get; set; }
        public virtual ICollection<UsuarioSistema> UsuarioSistema { get; set; }
    }
}
