//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tercero
    {
        public Tercero()
        {
            this.EncabezadoConvenio = new HashSet<EncabezadoConvenio>();
            this.Contacto = new HashSet<Contacto>();
            this.Sello_Distribuidor = new HashSet<Sello_Distribuidor>();
            this.Sello_Distribuidor1 = new HashSet<Sello_Distribuidor>();
            this.EncabezadoPelicula = new HashSet<EncabezadoPelicula>();
            this.EncabezadoVentaEmpresarial = new HashSet<EncabezadoVentaEmpresarial>();
            this.Pqrs = new HashSet<Pqrs>();
            this.OportunidadVenta = new HashSet<OportunidadVenta>();
            this.Teatro = new HashSet<Teatro>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> TipoTerceroID { get; set; }
        public string Identificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> CiudadID { get; set; }
        public string Descripcion { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> TipoIdentificacionID { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> SexoID { get; set; }
        public Nullable<int> RowIDCentral { get; set; }
        public Nullable<int> RowIDCreacion { get; set; }
        public Nullable<int> TeatroCreacion { get; set; }
        public Nullable<bool> ind_cliente { get; set; }
        public Nullable<bool> ind_proveedor { get; set; }
        public Nullable<bool> ind_empleado { get; set; }
        public Nullable<bool> ind_accionista { get; set; }
        public Nullable<bool> ind_otros { get; set; }
        public Nullable<bool> ind_interno { get; set; }
        public Nullable<int> ERPRowID { get; set; }
    
        public virtual ICollection<EncabezadoConvenio> EncabezadoConvenio { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual ICollection<Contacto> Contacto { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Opcion Opcion1 { get; set; }
        public virtual Opcion Opcion2 { get; set; }
        public virtual ICollection<Sello_Distribuidor> Sello_Distribuidor { get; set; }
        public virtual ICollection<Sello_Distribuidor> Sello_Distribuidor1 { get; set; }
        public virtual ICollection<EncabezadoPelicula> EncabezadoPelicula { get; set; }
        public virtual ICollection<EncabezadoVentaEmpresarial> EncabezadoVentaEmpresarial { get; set; }
        public virtual ICollection<Pqrs> Pqrs { get; set; }
        public virtual ICollection<OportunidadVenta> OportunidadVenta { get; set; }
        public virtual ICollection<Teatro> Teatro { get; set; }
    }
}
