//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoSolicitud
    {
        public TipoSolicitud()
        {
            this.Pqrs = new HashSet<Pqrs>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Opcion Opcion { get; set; }
        public virtual ICollection<Pqrs> Pqrs { get; set; }
    }
}
