//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TvShowListaPrecios
    {
        public int RowIDTarifa { get; set; }
        public int RowIDEncabezado { get; set; }
        public string Dias { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> PrecioTCR { get; set; }
        public string Formato { get; set; }
        public string TipoTarifa { get; set; }
        public string Teatro { get; set; }
        public string Servicio { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<System.TimeSpan> HoraInicial { get; set; }
        public Nullable<System.TimeSpan> HoraFinal { get; set; }
        public Nullable<int> RowIDGrupoDias { get; set; }
        public string GrupoDias { get; set; }
        public Nullable<int> PrecioTCR { get; set; }
    }
}
