//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVShowTrailers
    {
        public int RowID { get; set; }
        public string Trailer { get; set; }
        public string Afiche { get; set; }
        public string Formato { get; set; }
        public string Nombre { get; set; }
        public string Vers { get; set; }
        public string Clasf { get; set; }
    }
}
